server:
  port: 8503
spring:
  application:
    name: notification-microservice
  rabbitmq:
    username: j4v4developers
    password: j4v4developers
  cloud:
    stream:
      bindings:
        input:
          destination: notificationqueue
eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

#Output: kuyruğumuza girdi yapacak kişi
#Input: Kuyruğumuzu dinleyecek kişi (notification-microservice)